export const ROMAJI_REPLACEMENTS: [string, string][] = [
    ["shi", "si"],
    ["chi", "ti"],
    ["tsu", "tu"],
    ["fu", "hu"],
    ["ji", "zi"],
    ["sha", "sya"],
    ["sho", "syo"],
    ["shu", "syu"],
    ["cha", "tya"],
    ["cho", "tyo"],
    ["chu", "tyu"],
];

export const CLASSROOM_PATTERNS: RegExp[] = [
    /^(.+?)\s*さんが\s*(.+?)\s*を使用して新しい課題を投稿しました:\s*(.+)$/,
    /^(.+?)\s*さんが\s*(.+?)\s*を使用して(.+?)を投稿しました:\s*(.+)$/,
    /^(.+?)\s*さんが\s*(.+?)\s*を使用して(.+?)を投稿しました\.?\s*(.*)$/,
    /^(.+?)\s*さんが\s*(.+?)\s*を投稿しました:\s*(.+)$/,
    /^(.+?)\s*さんが\s*(.+?)\s*を投稿しました\.?\s*(.*)$/,
    /^(.+?)\s*さんが\s*(.+?)\s*を投稿しました\.?$/,
    /^(.+?)\s*さんが\s*(.+?)\s*をしました\.?$/,
    /^(.+?)\s*さんが\s*(.+?)しました\.?$/,
];

export const TARGET_SELECTORS: string = [
    'span[class*="VGBb"]',
    'div[class*="VGBb"]',
    'div[class*="QRIHxd"]',
    'div[class*="usn0cc"]',
    'div[class*="iOB96"]',
    'span[class*="post"]',
    'div[class*="post"]',
    'span[class*="message"]',
    'div[class*="message"]',
    'span[class*="content"]',
    'div[class*="content"]',
    'span[class*="text"]',
    'div[class*="text"]',
    'span[class*="body"]',
    'div[class*="body"]',
    'span[class*="description"]',
    'div[class*="description"]',
    'span[class*="Pc9Gce"]',
    'div[class*="Pc9Gce"]',
    'span[class*="DShyMc"]',
    'div[class*="DShyMc"]',
    'span[class*="wJD2Bb"]',
    'div[class*="wJD2Bb"]',
    'span[class*="YMvIgc"]',
    'div[class*="YMvIgc"]',
    'span[class*="CYZpAe"]',
    'div[class*="CYZpAe"]',
    'span[class*="YVvGBb"]',
    'div[class*="YVvGBb"]',
    'span[class*="asQXV"]',
    'div[class*="asQXV"]',
    'span[class*="announcement"]',
    'div[class*="announcement"]',
    'span[class*="assignment"]',
    'div[class*="assignment"]',
    'span[class*="stream"]',
    'div[class*="stream"]',
].join(", ");

export const DROPDOWN_SELECTORS = [
    'ul[role="listbox"]',
    '[role="listbox"]',
    '[role="menu"]',
    'div[class*="VfPpkd-xl07Ob"]',
    'div[class*="VfPpkd-StrnGf"]',
    'ul[class*="dropdown"]',
    'div[class*="dropdown-menu"]',
];

export const ITEM_SELECTORS = [
    '[role="option"]',
    '[role="menuitem"]',
    'li[class*="VfPpkd"]',
    'div[class*="VfPpkd-rymPhb"]',
];
